config/routes.rb
DietApp::Application.routes.draw do
  root 'base#about'

  resources :profiles
  resources :products
  resources :dishes
  resources :ingredients
  resources :articles
  resources :dish_types
  resources :meals
  resources :menus

  get '/about' => 'base#about'
  get '/contact' => 'base#contact'
  get '/calendars/day/(:date)' => 'calendars#day'
  get '/calendars/month/(:year_month)' => 'calendars#month'

  

end

app/controllers/dish_types_controller.rb
class DishTypesController < ApplicationController
  before_action :set_dish_type, only: [:edit, :update, :destroy]

  def index
    @dish_types = DishType.all
    redirect_to new_dish_type_path if @dish_types.empty?
  end

  def new
    @dish_type = DishType.new
  end

  def edit
  end

  def create
    @dish_type = DishType.new(dish_type_params)
    if @dish_type.save
      redirect_to @dish_type, notice: 'Artykuł dodany do bazy'
    else
      render action: 'new'
    end
  end

  def update
    if @dish_type.update(dish_type_params)
      redirect_to @dish_type, notice: 'Artykuł został zaktualizowany'
    else
      render action: 'edit'
    end
  end

  def destroy
    @dish_type.destroy
    redirect_to dish_types_url
  end

  private

  def set_dish_type
    @dish_type = DishType.find(params[:id])
  end


  def dish_type_params
    params.require(:dish_type).permit(:name)
  end
end

app/views/dish_types/_form.html.erb
<%= form_for(@dish_type) do |f| %>
  <% if @dish_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish_type.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @dish_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Typ posiłku' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Zapisz typ posiłku" %>
  </div>
<% end %>

app/views/dish_types/edit.html.erb
<h1>Zmień nazwę typu posiłku</h1>

<%= render 'form' %>

<%= link_to 'Wróć do listy typów', dish_types_path %>

app/views/dish_types/index.html.erb
<h1>Typy posiłków:</h1>

<table>
  <% @dish_types.each do |dish_type| %>
    <tr>
      <td><%= dish_type.name %></td>
      <td><%= link_to 'Zmień', edit_dish_type_path(dish_type) %></td>
      <td><%= link_to 'Usuń', dish_type, method: :delete, data: { confirm: 'Na pewno chcesz usunąć ten typ?' } %></td>
  <% end %>
</table>

<%= link_to 'Dodaj nowy artykuł', new_dish_type_path %>

app/views/dish_types/new.html.erb
<h1>Nowy typ posiłku:</h1>

<%= render 'form' %>

<%= link_to 'Wróć', dish_types_path %>