config/routes.rb
DietApp::Application.routes.draw do
  root 'base#about'

  resources :profiles
  resources :products
  resources :dishes
  resources :ingredients
  resources :articles
  resources :dish_types
  resources :meals
  resources :menus

  get '/about' => 'base#about'
  get '/contact' => 'base#contact'
  get '/calendars/day/(:date)' => 'calendars#day'
  get '/calendars/month/(:year_month)' => 'calendars#month'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, message: "Podaj tytuł artykułu"
  validates_presence_of :author, message: "Podaj autora artykułu"
  validates_presence_of :content, message: "Podaj treść artykułu"
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
    redirect_to new_article_path if @articles.empty?
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: 'Artykuł dodany do bazy'
    else
      render action: 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Artykuł został zaktualizowany'
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :author, :source, :content)
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Tytuł' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author, 'Autor' %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :source, 'Źródło' %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :content, 'Treść' %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz artykuł" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edycja artykułu</h1>

<%= render 'form' %>

<%= link_to 'Wyświetl artykuł', @article %> |
<%= link_to 'Wróć do listy artykułów', articles_path %>

app/views/articles/index.html.erb
<h1>Artykuły:</h1>

<table>
  <thead>
    <tr>
      <th>Tytuł</th>
      <th>Autor</th>
      <th>Źródło</th>
      <th>Treść</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article %></td>
        <td><%= article.author %></td>
        <td><%= article.source %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Zmień', edit_article_path(article) %></td>
        <td><%= link_to 'Usuń', article, method: :delete, data: { confirm: 'Na pewno chcesz usunąć ten artykuł?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj nowy artykuł', new_article_path %>

app/views/articles/new.html.erb
<h1>Nowy artykuł:</h1>

<%= render 'form' %>

<%= link_to 'Wróć', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tytuł:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Źródło:</strong>
  <%= @article.source %>
</p>

<p>
  <strong>Treść:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Zmień', edit_article_path(@article) %> |
<%= link_to 'Wróć', articles_path %>