config/routes.rb
DietApp::Application.routes.draw do
  root 'base#about'

  resources :profiles
  resources :products
  resources :dishes
  resources :ingredients
  resources :articles
  resources :dish_types
  resources :meals
  resources :menus

  get '/about' => 'base#about'
  get '/contact' => 'base#contact'
  get '/calendars/day/(:date)' => 'calendars#day'
  get '/calendars/month/(:year_month)' => 'calendars#month'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, message: "Podaj nazwę produktu"
  validates_uniqueness_of :name, message: "Produkt o takiej nazwie już istnieje"
  validates_presence_of :protein, message: "Podaj ilość białka"
  validates_numericality_of :protein, message: "Ilość białka podana niepoprawnie"
  validates_presence_of :fat, message: "Podaj ilość tłuszczu"
  validates_numericality_of :fat, message: "Ilość tłuszczu podana niepoprawnie"
  validates_presence_of :carbs, message: "Podaj ilość węglowodanów"
  validates_numericality_of :carbs, message: "Ilość węglowodanów podana niepoprawnie"
  has_many :ingredients, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  include ProductsHelper

  def index
    @products = Product.all
    @product_values = {}
    @products.each do |product|
      protein_kcal, fat_kcal, carbs_kcal = grams_to_kcal(product)
      @product_values[product] = { protein: protein_kcal, fat: fat_kcal, carbs: carbs_kcal }
    end
    redirect_to new_product_path if @products.empty?
  end

  def show
    @protein_kcal, @fat_kcal, @carbs_kcal = grams_to_kcal(@product)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      count_calories(@product)
      redirect_to @product, notice: 'Produkt dodany do listy'
    else
      render action: 'new'
    end
  end

  def update
    if @product.update(product_params)
      count_calories(@product)
      redirect_to @product, notice: 'Produkt został zaktualizowany'
    else
      render action: 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :calories, :protein, :fat, :carbs)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_calories(product)
    calories = product.protein * 4 + product.fat * 9 + product.carbs * 4
    product.update(calories: calories.to_i)
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Podaj nazwę produktu' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :protein, 'Podaj zawartość białka na 100g' %><br>
    <%= f.text_field :protein %>
  </div>
  <div class="field">
    <%= f.label :fat, 'Podaj zawartość tłuszczu na 100g' %><br>
    <%= f.text_field :fat %>
  </div>
  <div class="field">
    <%= f.label :carbs, 'Podaj zawartość węglowodanów na 100g' %><br>
    <%= f.text_field :carbs %>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz produkt" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Zmień dane produktu</h1>

<%= render 'form' %>

<%= link_to 'Wyświetl produkt', @product %> |
<%= link_to 'Wróć do listy produktów', products_path %>

app/views/products/index.html.erb
<h1>Dostępne produkty</h1>

<table>
  <caption>Dla 100 g</caption>
  <thead>
    <tr>
      <th>Produkt</th>
      <th>Kalorie</th>
      <th>Białko</th>
      <th>Tłuszcze</th>
      <th>Węglowodany</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_values.each do |product, product_values| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= "#{product.calories} kcal" %></td>
        <td><%= "#{product.protein} g (#{product_values[:protein]} kcal)" %></td>
        <td><%= "#{product.fat} g (#{product_values[:fat]} kcal)" %></td>
        <td><%= "#{product.carbs} g (#{product_values[:carbs]} kcal)" %></td>
        <td><%= link_to 'Zmień', edit_product_path(product) %></td>
        <td><%= link_to 'Usuń', product, method: :delete, data: { confirm: 'Na pewno chcesz usunąć produkt?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj nowy produkt', new_product_path %>

app/views/products/new.html.erb
<h1>Dodaj nowy produkt</h1>

<%= render 'form' %>

<%= link_to 'Wróć do listy produktów', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @product.name.capitalize %></h1>

<table>
  <caption>Wartości w 100 g</caption>
  <tr>
    <td>Kalorie:</td>
    <td><%= "#{@product.calories} kcal" %></td>
  </tr>
  <tr>
    <td>Białko:</td>
    <td><%= "#{@product.protein} g (#{@protein_kcal} kcal)" %></td>
  </tr>
  <tr>
    <td>Tłuszcze:</td>
    <td><%= "#{@product.fat} g (#{@fat_kcal} kcal)" %></td>
  </tr>
  <tr>
    <td>Węglowodany:</td>
    <td><%= "#{@product.carbs} g (#{@carbs_kcal} kcal)" %></td>
  </tr>
</table>

<%= link_to 'Zmień', edit_product_path(@product) %> |
<%= link_to 'Wróć do listy produktów', products_path %>