config/routes.rb
DietApp::Application.routes.draw do
  root 'base#about'

  resources :profiles
  resources :products
  resources :dishes
  resources :ingredients
  resources :articles
  resources :dish_types
  resources :meals
  resources :menus

  get '/about' => 'base#about'
  get '/contact' => 'base#contact'
  get '/calendars/day/(:date)' => 'calendars#day'
  get '/calendars/month/(:year_month)' => 'calendars#month'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf8">
  <title>Jedzeniowo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", cache: true %>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav id="navigation">
      <h1>Jedzeniowo</h1>
      <ul>
        <li><%= link_to 'O nas', controller: 'base', action: 'about' %></li>
        <li><%= link_to 'Produkty', products_path %></li>
        <li><%= link_to 'Profile', profiles_path %></li>
        <li><%= link_to 'Dania', dishes_path %></li>
        <li><%= link_to 'Typy posiłków', dish_types_path %></li>
        <li><%= link_to 'Jadłospisy', menus_path %></li>
        <li><%= link_to 'Kalendarz', controller: 'calendars', action: 'month' %></li>
      </ul>
    </nav>
  </header>
  <section>

    <%= yield %>

  </section>
</body>
</html>